train_dir    : 'data/graph_data/train'
valid_dir    : 'data/graph_data/valid'
param_dir    : 'params/'
log_dir      : 'logs/comparisons/qgnn/arch_comparison/embedding_learning/'
run_type     : 'new_run'
gpu          : '5'
n_files      : 1600
n_valid      : 200
n_train      : 1400
lr           : 0.001
n_iters      : 2
n_epoch      : 1
TEST_every   : 50
hid_dim      : 1
network      : 'TEST'
n_thread     : 2
log_verbosity: 1

